- name: Install the machine pre-requistes
  hosts: localhost
  pre_tasks:
    - name: Allow '{{ ansible_user_id }}' to have passwordless sudo
      become: true
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^{{ ansible_user_id }}'
        line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add docker-ce repository
      become: true
      yum_repository:
        name: docker-ce
        description: docker-ce repo
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install needed packages
      become: true
      dnf:
        name: '{{item }}'
        state: latest
      loop:
        - libselinux-python
        - jq
        - figlet
        - pass
        - signal-desktop
        - numlockx

    - name: Disable SELinux
      selinux:
        state: disabled

  roles:
    - name: i3wm
      tags: i3wm

    - name: terminator
      tags: terminator

    - name: zsh
      tags: zsh

    - name: nvim
      tags: nvim

    - name: python
      tags: python

    - name: golang
      become: true
      tags: golang

    - name: kubernetes
      tags: kubernetes

    - name: gcloud
      become: true
      tags: gcloud

    - name: rambox
      tags: rambox
