- name: Install the machine pre-requistes
  hosts: localhost
  pre_tasks:
    - name: Allow '{{ ansible_user_id }}' to have passwordless sudo
      become: true
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^{{ ansible_user_id }}'
        line: '{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


    - name: Get current username
      set_fact:
        user: '{{ lookup("env", "USER") }}'

    - include_role:
        name: base

  roles:
    - name: i3wm
      tags: i3wm

    - name: terminator
      tags: terminator

    - name: zsh
      tags: zsh

    - name: nvim
      tags: nvim

    - name: python
      tags: python

    - name: golang
      become: true
      tags: golang

    - name: kubernetes
      tags: kubernetes
