- name: Install the machine pre-requistes
  hosts: localhost
  pre_tasks:
    - name: Add docker-ce repository
      become: true
      yum_repository:
        name: docker-ce
        description: docker-ce repo
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Install needed packages
      become: true
      dnf:
        name: '{{item }}'
        state: latest
      loop:
        - terminator
        - python3-ipython
        - python3-black
        - python3-neovim
        - pipenv
        - powerline-fonts
        - highlight
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - jq
        - figlet
        - pass


  roles:
    - name: golang
      become: true
    - name: zsh
    - name: nvim
    - name: kubernetes
    - name: gcloud
      become: true

