- name: Install needed packages
  become: true
  dnf:
    name: '{{item }}'
    state: latest
  loop:
    - python3-ipython
    - python3-black
    - python3-neovim
    - pipenv

- name: Add serve function
  blockinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    marker: '# {mark} PYTHON SERVE FUNCTION'
    block: |
      function serve() {
        dir=$1
        cd $dir
        python3 -m http.server
        cd -
      }
