- name: Add docker-ce repository
  become: true
  yum_repository:
    name: docker-ce
    description: docker-ce repo
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo

- name: pre-requistes
  become: true
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- include: kubectl.yaml
- include: k9s.yaml
- include: minikube.yaml
