- name: Install KVM2
  become: true
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - bridge-utils
    - libvirt
    - virt-install
    - qemu-kvm
    - '@virtualization'

- name: Get the binary
  become: true
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/bin/minikube
    remote_src: true
    owner: root
    group: root
    mode: 0755

- name: Set KVM2 as a default VM driver for Minikube
  shell: minikube config set vm-driver kvm2



- name: Download docker-machine-driver-kvm2 installer
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
    dest: /tmp/docker-machine-driver-kvm2
    mode: 0775
    #  when: not oh_my_zsh_folder.stat.exists

- name: Execute /tmp/docker-machine-driver-kvm2
  become: true
  script: /tmp/docker-machine-driver-kvm2 /usr/local/bin/
  #  when: not oh_my_zsh_folder.stat.exists

- name: Remove /tmp/docker-machine-driver-kvm2
  file:
    path: /tmp/docker-machine-driver-kvm2
    state: absent
    #  when: not oh_my_zsh_folder.stat.exists
