- name: Get terminator
  become: true
  package:
    name: 'terminator'
    state: latest

- name: Create terminator folders
  file:
    path: '{{ ansible_env.HOME }}/.config/terminator'
    state: directory
    recurse: true

- name: Set terminator configuration
  copy:
    src: config
    dest: '{{ ansible_env.HOME }}/.config/terminator/config'

