- name: Install i3 and dependencies
  become: true
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - i3
    - i3status
    - dmenu
    - xbacklight
    - feh
    - conky
    - xrandr
    - i3lock
    - 'http://download-ib01.fedoraproject.org/pub/fedora/linux/releases/30/Everything/x86_64/os/Packages/g/giblib-1.2.4-28.fc28.x86_64.rpm'
    - scrot
    - ImageMagick
    - xautolock
    - fontawesome-fonts
    - powerline-fonts
    - highlight
    - pulseaudio
    - pavucontrol
    - numlockx
    - nautilus
    - python3-netifaces

- name: Ensure i3 mandatory folders exist
  file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: directory
    recurse: true
  loop:
    - '.config/i3'
    - 'screenshots'

- name: Get Bumblebee status bar
  git:
    repo: https://github.com/tobi-wan-kenobi/bumblebee-status.git
    dest: '{{ ansible_env.HOME }}/.config/i3/bumblebee-status'

- name: Set i3wm configuration
  copy:
    src: config
    dest: '{{ ansible_env.HOME }}/.config/i3'

- name: Copy i3wm scripts
  copy:
    src: '{{ item }}'
    dest: '{{ ansible_env.HOME }}/.config/i3/'
    mode: 0775
  loop:
    - lock.sh
    - monitor.sh
