- name: Get nvim 
  get_url:                                                                              
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /usr/bin/nvim                                                                                                      
    owner: root
    group: root
    mode: 0775

- name: Getvim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim'

- name: Set vim configuration
  copy:
    src: init.vim 
    dest: '{{ ansible_env.HOME }}/.config/nvim/init.vim'
  notify:
    - refresh vim conf

